services:
  bus-worker:
    image: ghcr.io/dragon863/myrunshaw-bus-worker:v1.0.2
    env_file:
      - src/bus-worker/.env
    restart: unless-stopped
    container_name: myrunshaw-bus-worker
    network_mode: host
    environment:
      - TZ=Europe/London

  api:
    image: ghcr.io/dragon863/myrunshaw-api:v1.0.2
    env_file:
      - src/api/.env
    restart: unless-stopped
    container_name: myrunshaw-api
    network_mode: host
    environment:
      - TZ=Europe/London

  sync_engine:
    image: ghcr.io/dragon863/myrunshaw-sync-engine:v1.0.2
    env_file:
      - src/sync-engine/.env
    restart: no
    container_name: myrunshaw-sync-engine
    network_mode: host
    environment:
      - TZ=Europe/London

  name_cache:
    image: ghcr.io/dragon863/myrunshaw-name-cache:v1.0.2
    env_file:
      - src/name-cache/.env
    restart: unless-stopped
    container_name: myrunshaw-redis-webhook-engine
    network_mode: host
    environment:
      - TZ=Europe/London
