services:
  bus-worker:
    build: 
      context: src/bus-worker
    env_file:
      - src/bus-worker/.env
    restart: unless-stopped
    container_name: myrunshaw-bus-worker
    network_mode: host
    environment:
      - TZ=Europe/London

  api:
    build: 
      context: src/api
    env_file:
      - src/api/.env
    restart: unless-stopped
    container_name: myrunshaw-api
    network_mode: host
    environment:
      - TZ=Europe/London

  sync_engine:
    build: 
      context: src/sync-engine
    env_file:
      - src/sync-engine/.env
    restart: no # This is a task run by a cron job daily
    container_name: myrunshaw-sync-engine
    network_mode: host
    environment:
      - TZ=Europe/London