version: '3.8'

services:
  app:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    container_name: runshaw-friends-api
